# Working through content to see if I want to use for my teaching demo
# R for Reproducible Scientific Analysis - Exploring Data Frames
# The lesson I want to consider is 5 (Exploring Data Frames), but I'm working through Lessons 1-5 below

##  LESSON 1: INTRODUCTION TO R AND RSTUDIO

1+100
# running code, Command + Return (MAC); Control + Return (WINDOWS)
# if you get + in the console, hit esc
# order of operations same as in school, from highest to lowest precedence: 
# parentheses (,)
# exponents: ^ or **
# multiply: *
# divide: /
# add: + 
# substract: -
3+5*2
# use parentheses to group operations differently
(3+5) * 2
# really large or small numbers gets scientific notation
2/10000
# you can write in scientific notation
5e3

# Functions take arguments as inputs; anything we type inside the parentheses is considered an argument; number of arguments may vary from none to multiple

getwd() #doesn't require any input
sin(1) #requires input
log(1) #requires input
log10(10) #requires input
exp(0.5) #requires input
?exp #getting help

# Comparing Things

1==1 #equality (== reads as "is equal to")
1!=2 #inequality (!= reads as "is not equal to")
1<2
1<=2 #less than or equal to
1>0
1>=-9 #greater than or equal to

# Variables and Assignment

x <- 1/40
x
log(x)
x <- 100 #x is now reassigned
#the right-hand side of the assignment operator is fully evaluated before the assignment occurs

#variable names can contain letters, numbers, underscores, and periods but not spaces; variable names can't start with a number or an underscore
#variables beginning with a period are HIDDEN VARIABLES; GOOD REMINDER! 
#some people do periods.between.words
#some people do underscores_between_words
#some people do camelCaseToSeparateWords ; whatever you do, be consistent

# Vectorization
#R is vectorized, meaning that variables and functions can have vectors as values
#In contrast to physics and mathematics, a vector in R describes a set of values in a certain order of the same data type

1:5
2^(1:5)
x<- 1:5
2^x

# Managing your Environment
ls() #will list all variables and functions stored in the global environment
#like in the shell, ls() won't show hidden variables (".") by default
ls(all.names = TRUE) #will show all objects; GOOD TO KNOW! 

ls #what happens if you run ls without parentheses? Prints a bunch of code instead of list of objects. Why? 
#like everything in R, ls is the name of an object and when you run the name of an object, it prints the contents; the contents in this case are the R code that makes the ls function work; GOOD TO KNOW!

rm(x) #use to remove objects you no longer need

#if you have lots of things in your environment and want to delete all of them, you can pass the results of ls to the rm function
#like order of operations, anything inside the innermost parentheses is evaluated first, and so on; GOOD TO REMEMBER! 
rm(list = ls())

# R Packages
installed.packages() #to see what packages are installed
install.packages("packagename") #to install package
update.packages() #to update package
remove.packages("packagename") #to remove package
library(package) #to make package available for use

##  LESSON 2: PROJECT MANAGEMENT WITH RSTUDIO

#How to create a self-contained project (I already do this)

#Best practices for project organization

#Treat data as read only - working with data interactively (e.g., Excel) where it can be modified means you are never sure of where the data came from, or how it has been modified; treat your data as read only

#Data cleaning - in many cases, your data will be "dirty" and need significant preprocessing to get into a format R will find useful; this task is sometimes called "data munging" (never heard of that); storing these scripts in a separate folder, and creating a second "read-only" data folder to hold the "cleaned" data sets can prevent confusion between the two sets

#Treat generated output as disposable - anything generated by your scripts should be treated as disposable; it should be able to be regenerated from your scripts; some recommendations - "doc" for text docs, "data" for raw data and metadata, "results" for files generated, "src" for scripts and programs, "bin" programs from elsewhere

#Version control - important to use with projects


